added visual blocks docs
tinacms/tinacms.org pull request #1252
Opened 2022-03-04 15:21 UTC by logan-anderson

closes #1234

2022-03-04 17:48 UTC, perkinsjr requested changes

2022-03-04 17:48 UTC, perkinsjr commented on content/docs/editing/blocks.md
> +This visual block selector allows editors to select blocks from a a set images instead of text.
Grammar.. You have "from a a set"

2022-03-04 17:51 UTC, spbyrne commented
I should mention both `category` and `previewSrc` are optional; if a preview isn't provided the block will still be available with a title to click on, just no preview.

2022-03-07 18:12 UTC, logan-anderson commented on content/docs/editing/blocks.md
> +This visual block selector allows editors to select blocks from a a set images instead of text.
Thanks @perkinsjr it has been fixed

2022-03-07 18:13 UTC, logan-anderson commented
> I should mention both `category` and `previewSrc` are optional; if a preview isn't provided the block will still be available with a title to click on, just no preview.

@spbyrne updated docs to reflect this.

2022-03-10 00:11 UTC, perkinsjr approved these changes

2022-03-10 15:02 UTC, merged