Docs update for tinacms/tinacms#1704
tinacms/tinacms.org pull request #792
Opened 2021-02-05 06:03 UTC by austincondiff

Adds documentation for the radio group field in tinacms/tinacms#1704.

__Note:__ I was unable to test this because I do not have an `.env` with GitHub client id and secret so my dev server will not start.

2021-02-05 08:56 UTC, DirtyF reviewed
Thanks @austincondiff this is awesome 🤩 

From a quick first look at the deploy preview https://tinacms-site-n-git-fork-austincondiff-docs-fields-radi-30e617.tinacms.vercel.app/docs/plugins/fields/radio-group/ 

- [ ] radio-field is not displayed in the sidebar navigation
- [x] ~~images do not appear~~

2021-02-05 08:59 UTC, DirtyF commented
@austincondiff Do https://tina.io/guides/nextjs/github/github-oauth-app/ help to set up local env variables?

2021-02-05 15:57 UTC, DirtyF requested changes
@austincondiff for the page to be linked in the sidebar nav, you need to add manually an entry in the `content/toc-doc.json` line 141 between `toggle` and `select` fields: 

```json
                    {
                        "id": "/docs/plugins/fields/radio-group",
                        "slug": "/docs/plugins/fields/radio-group",
                        "title": "Radio Group"
                    },
```

2021-02-05 15:57 UTC, DirtyF commented on content/docs/plugins/fields/radio-group.md
> +![TinaCMS Radio Group Field using a "radio" variant in a "horizontal" direction](/img/fields/radio-group-field-horizontal-radio.png)
```suggestion
![TinaCMS Radio Group Field using a "radio" variant in a "horizontal" direction](/img/fields/radio-group-field-horizontal-radio.gif)
```

2021-02-05 15:57 UTC, DirtyF commented on content/docs/plugins/fields/radio-group.md
> +![TinaCMS Radio Group Field using a "radio" variant in a "vertical" direction](/img/fields/radio-group-field-vertical-radio.png)
```suggestion
![TinaCMS Radio Group Field using a "radio" variant in a "vertical" direction](/img/fields/radio-group-field-vertical-radio.gif)
```

2021-02-05 15:57 UTC, DirtyF commented on content/docs/plugins/fields/radio-group.md
> +![TinaCMS Radio Group Field using a "button" variant in a "horizontal" direction](/img/fields/radio-group-field-horizontal-button.png)
```suggestion
![TinaCMS Radio Group Field using a "button" variant in a "horizontal" direction](/img/fields/radio-group-field-horizontal-button.gif)
```

2021-02-05 15:57 UTC, DirtyF commented on content/docs/plugins/fields/radio-group.md
> +![TinaCMS Radio Group Field using a "button" variant in a "vertical" direction](/img/fields/radio-group-field-vertical-button.png)
```suggestion
![TinaCMS Radio Group Field using a "button" variant in a "vertical" direction](/img/fields/radio-group-field-vertical-button.gif)
```

2021-02-05 16:39 UTC, austincondiff commented
The sidebar entry should be there now. ✅

We may at some point may look into making the sidebar editable by the cms and automating the prev/next links so that doesn't have to be done manually (unless we want more control by not doing so).

2021-02-06 10:30 UTC, DirtyF approved these changes

2021-02-08 20:10 UTC, merged