Page: Tina Cloud updates
tinacms/tinacms.org pull request #843
Opened 2021-04-28 12:04 UTC by DirtyF

- Text copy changes. 
- Branching is not available yet on Tina Cloud

2021-05-13 11:43 UTC, jamespohalloran requested changes

2021-05-13 12:01 UTC, DirtyF commented on content/pages/cloud.json
> +          "subline": "Tina Cloud brings authentication, user management, roles. Onboard your team in no time, no GitHub accounts required.",
```suggestion
          "subline": "Tina Cloud brings authentication, user management, roles. Onboard your team in no time, no GitHub accounts for editors required.",
```

2021-05-13 12:03 UTC, DirtyF commented on content/pages/cloud.json
> +          "subline": "Tina Cloud brings authentication, user management, roles. Onboard your team in no time, no GitHub accounts for editors required.",
@jamespohalloran fixed :)

2021-05-17 19:18 UTC, jamespohalloran requested changes

2021-05-17 19:18 UTC, jamespohalloran commented on content/pages/cloud.json
> +          "subline": "Visual editing greatly improves the productivity of content teams and make their job much more enjoyable. You team can work with full confidence, powerful Git Version Control ha
```suggestion
          "subline": "Visual editing greatly improves the productivity of content teams and makes their job much more enjoyable. Your team can work with full confidence. Powerful Git version control has your back."
```

2021-05-17 19:18 UTC, jamespohalloran commented on content/pages/cloud.json
> +          "subline": "Tina Cloud Content API provides a GraphQL interface to your repositories files to bring data integrity and relationships to your filesystem.\nStore your content in open formats
```suggestion
          "subline": "Tina Cloud Content API provides a GraphQL interface to your repositories' files, bringing data integrity and relationships to your filesystem.\nStore your content in open formats like Markdown and JSON to ease content re-use and migrations."
```

> bringing data integrity and relationships to your filesystem.

"Filesystem" throws me off here. Might just be me, but maybe this is clearer?:

> bringing data integrity and relationships to your files' content.

(Github has a GraphQL Api for files, but our values comes from querying the content within them).

2021-05-17 20:29 UTC, DirtyF commented on content/pages/cloud.json
> +          "subline": "Tina Cloud Content API provides a GraphQL interface to your repositories' files, bringing data integrity and relationships to your filesystem.\nStore your content in open format
```suggestion
          "subline": "Tina Cloud Content API provides a GraphQL interface to your repositories' files, bringing data integrity and relationships to your content files.\nStore your content in open formats like Markdown and JSON to ease content re-use and migrations."
```

2021-06-24 18:25 UTC, closed without merging