Updates Docs around DateField Plugin
tinacms/tinacms.org pull request #860
Opened 2021-05-12 19:11 UTC by Enigmatical

Because the `DateFieldPlugin` is being moved back into core, we're not longer suggesting users add the `react-tinacms-date` package.

I've moved the README for that package into the core docs, formatted similarly to other field pages.

**Developer's Note:**
`_app.txs` and `package.json` for this repo currently use the `react-tinacms-date` package.  I wasn't sure if it should be part of this PR or not, but we'll want to remove those dependencies once TinaCMS Core has the `DateFieldPlugin`.

2021-05-12 20:06 UTC, DirtyF approved these changes
LGTM

2021-05-13 12:23 UTC, logan-anderson commented
Looks good to me as well!

2021-05-14 14:27 UTC, dwalkr commented on content/docs/plugins/fields/date.md
> +> **Prior to v0.40.1, `DateFieldPlugin` was not a default plugin.** See the [react-tinacms-date](/packages/react-tinacms-date) docs for instructions on how to use the `date` field for previous versio
```suggestion
> **Prior to v0.41.0, `DateFieldPlugin` was not a default plugin.** See the [react-tinacms-date](/packages/react-tinacms-date) docs for instructions on how to use the `date` field for previous versions.
```
current RC is 0.41.0

2021-05-14 14:28 UTC, dwalkr requested changes
Looks good! I'm just gonna block this until 0.41.0 gets released

2021-05-17 17:16 UTC, dwalkr approved these changes

2021-05-17 17:16 UTC, merged