intial changes to cloud starter guide
tinacms/tinacms.org pull request #948
Opened 2021-07-23 18:47 UTC by ashleyjanedoiron

Initial changes to the cloud starter guide found here (https://tina.io/guides/tina-cloud/starter/overview/)

Still to do:
- add in newly styled starter GIFs.
- verify the starter structure page

2021-07-26 08:54 UTC, DirtyF commented on content/guides/tina-cloud/starter/create-account.md
> +1. Visit <a href="https://auth.tina.io/register" target="_blank">auth.tina.io</a>, create an account, and signin.
```suggestion
1. Visit <a href="https://app.tina.io/register" target="_blank">auth.tina.io</a>, create an account, and signin.
```

Shouldn't it be the new URL here?

2021-07-26 08:58 UTC, DirtyF commented on content/guides/tina-cloud/starter/structure.md
> +If you have a GraphQL client like [Altair](https://altair.sirmuel.design/) go to `http://localhost:4001/graphql` to browse the docs and query our GraphQL API.
We now embed Altair by default.

```suggestion
To browse the docs and query our GraphQL API, run 'yarn dev` in your Tina project and go to `http://localhost:4001/altair`.
```

2021-07-26 19:38 UTC, jeffsee55 submitted a review, later dismissed

2021-07-27 11:48 UTC, perkinsjr commented
@ashleyjanedoiron looks great, we can merge this tomorrow.

2021-07-27 16:26 UTC, jamespohalloran commented
> @ashleyjanedoiron looks great, we can merge this tomorrow.

Could this be merged now? I'm fine waiting, but it might help us avoid stepping on toes as we test things out today.

2021-07-27 16:28 UTC, perkinsjr commented
If the new starter is out we can absolutely do that.

2021-07-27 16:30 UTC, jamespohalloran commented
Thoughts @spbyrne ?

2021-07-27 17:36 UTC, logan-anderson commented
@jamespohalloran @perkinsjr The new stater is already out

2021-07-27 17:42 UTC, ashleyjanedoiron commented
> > @ashleyjanedoiron looks great, we can merge this tomorrow.
> 
> Could this be merged now? I'm fine waiting, but it might help us avoid stepping on toes as we test things out today.

I believe @jeffsee55  is working to merge his branch (https://github.com/tinacms/tinacms.org/pull/951) into this one. And then I'm going to add in a few notes from @logan-anderson's comments from earlier today. And then this will be good to go.

2021-07-27 18:16 UTC, logan-anderson commented
On the deploy page

> Connect to your GitHub repository and set the same environment variables as the ones in your env.local file:
> `NEXT_PUBLIC_TINA_CLIENT_ID= <YOUR_CLIENT_ID>`
> 🎉 Congratulations, your site is now live!

Only doing this doesn’t seem to work I was getting a lot of errors.
We also need to
1.  update the Tina Cloud app URL to match the production URL. (OR  create a new app)
2. Add another env var on vercel
```
NEXT_PUBLIC_USE_LOCAL_CLIENT=0
```
Once I did this I was able to edit my production site

2021-07-27 18:35 UTC, logan-anderson commented
We also didn’t talk about media. Since this guide is going to take place of the readme should myself or @jbevis Write a section of how to add media in it?

2021-07-27 18:38 UTC, perkinsjr commented
@logan-anderson that would be great!

2021-07-27 18:53 UTC, logan-anderson commented
@jbevis If you have time you can add it in. If not I can do it tomorrow morning.

2021-07-27 18:57 UTC, logan-anderson requested changes

2021-07-27 18:57 UTC, logan-anderson commented on content/guides/tina-cloud/starter/local.md
> +Click on the pencil in the lower left-hand corner to open Tina's sidebar which displays a variety of forms with fields you can edit and see updates live on the page. Since we're working locally, clic
They will also have to enter edit mode by going to http://localhost:3000/admin

2021-07-28 10:25 UTC, perkinsjr approved these changes

2021-07-28 10:26 UTC, perkinsjr approved these changes
LGTM

2021-07-28 12:00 UTC, logan-anderson approved these changes
🎉

2021-07-28 12:02 UTC, merged